name: Build and Deploy to External Repo

on:
  push:
    branches:
      - main
    pull_request:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run the tests
        run: npm test

      - name: Build
        run: npm run build
          
      - name: Deploy to Repo B
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          npm run deploy
        env:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          repository: ${{ github.repository }}